### ISSUE TITLE
data.NotEnoughCaptchaException

### ISSUE THREAD

**Issue by 3c** [lonnyzhang423/zhihu-captcha#1]
python3 model.py

```
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2018-03-22 16:36:22.195513: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Step: 0 Loss: 0.699411
Traceback (most recent call last):
  File "/Users/cx/workspace/ai/zhihu-captcha/data.py", line 83, in next_text_and_image
    line = next(captcha_file)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model.py", line 152, in <module>
    start_train()
  File "model.py", line 148, in start_train
    raise e
  File "model.py", line 138, in start_train
    logs, acc = sess.run([merged, accuracy], feed_dict=feed_dict(False))
  File "model.py", line 106, in feed_dict
    x, y = next_batch()
  File "/Users/cx/workspace/ai/zhihu-captcha/data.py", line 96, in next_batch
    text, image = next_text_and_image()
  File "/Users/cx/workspace/ai/zhihu-captcha/data.py", line 88, in next_text_and_image
    raise NotEnoughCaptchaException()
data.NotEnoughCaptchaException
```

**Comment by lonnyzhang423** [comment]
git上只上传了100多张验证码，请到网盘下载替换掉，重新运行
